### ISSUE TITLE
Issue with updating static files

### ISSUE THREAD

**Issue by aankit** [nycdoe-cs4all/blueprint-learning-site#59]
Expected: update static style.css file by activating virtualenv and running collectstatic.

Currently: permission denied
(env) aankit@blueprint:/home/sam/blueprint-learning-site$ ./manage.py collectstatic

You have requested to collect static files at the destination
location as specified in your settings:

    /home/sam/blueprint-learning-site/static

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/sam/blueprint-learning-site/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/sam/blueprint-learning-site/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/sam/blueprint-learning-site/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/sam/blueprint-learning-site/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/sam/blueprint-learning-site/env/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 193, in handle
    collected = self.collect()
  File "/home/sam/blueprint-learning-site/env/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 124, in collect
    handler(path, prefixed_path, storage)
  File "/home/sam/blueprint-learning-site/env/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 337, in copy_file
    if not self.delete_file(path, prefixed_path, source_storage):
  File "/home/sam/blueprint-learning-site/env/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 287, in delete_file
    self.storage.delete(prefixed_path)
  File "/home/sam/blueprint-learning-site/env/local/lib/python2.7/site-packages/django/core/files/storage.py", line 388, in delete
    os.remove(name)
OSError: [Errno 13] Permission denied: '/home/sam/blueprint-learning-site/static/css/style.css'

Also tried to run it as su:
(env) aankit@blueprint:/home/sam/blueprint-learning-site$ sudo ./manage.py collectstatic
Traceback (most recent call last):
  File "./manage.py", line 17, in <module>
    "Couldn't import Django. Are you sure it's installed and "
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

**Comment by aankit** [comment]
Sam created permissions group and added the sam and aankit users to it.
